-- Initial schema for a new PostgreSQL 16 database. Applied by Flyway.
-- COBIP mobile app: initial PostgreSQL schema.


CREATE TABLE users (
    user_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email varchar(255) NOT NULL,
    nickname varchar(50) NOT NULL UNIQUE,
    password_hash varchar(255) NOT NULL,
    role varchar(20) NOT NULL DEFAULT 'USER'
        CHECK (role IN ('USER', 'ADMIN')),
    status varchar(20) NOT NULL DEFAULT 'ACTIVE'
        CHECK (status IN ('ACTIVE', 'SUSPENDED', 'WITHDRAWN')),
    email_verified boolean NOT NULL DEFAULT false,
    service_terms_agreed_at timestamptz NOT NULL,
    privacy_terms_agreed_at timestamptz NOT NULL,
    profile_media_id bigint UNIQUE,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT users_email_not_blank CHECK (btrim(email) <> ''),
    CONSTRAINT users_nickname_not_blank CHECK (btrim(nickname) <> '')
);

CREATE UNIQUE INDEX users_email_lower_uq ON users (lower(email));

-- Administrators can add programming languages without changing a CHECK constraint.
CREATE TABLE languages (
    language_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code varchar(30) NOT NULL UNIQUE,
    name varchar(50) NOT NULL UNIQUE,
    display_order integer NOT NULL UNIQUE CHECK (display_order > 0),
    is_active boolean NOT NULL DEFAULT true,
    CONSTRAINT languages_code_not_blank CHECK (btrim(code) <> ''),
    CONSTRAINT languages_name_not_blank CHECK (btrim(name) <> '')
);

INSERT INTO languages (code, name, display_order) VALUES
    ('JAVA', 'Java', 1),
    ('PYTHON', 'Python', 2),
    ('JAVASCRIPT', 'JavaScript', 3);

-- Root rows are app areas; children are filters such as cache/DB/network/log.
CREATE TABLE categories (
    category_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_category_id bigint REFERENCES categories (category_id),
    code varchar(50) NOT NULL UNIQUE,
    name varchar(50) NOT NULL,
    display_order integer NOT NULL CHECK (display_order > 0),
    is_active boolean NOT NULL DEFAULT true,
    CONSTRAINT categories_code_not_blank CHECK (btrim(code) <> ''),
    CONSTRAINT categories_name_not_blank CHECK (btrim(name) <> ''),
    CONSTRAINT categories_not_own_parent CHECK (parent_category_id IS DISTINCT FROM category_id)
);

CREATE UNIQUE INDEX categories_root_name_uq ON categories (name)
    WHERE parent_category_id IS NULL;
CREATE UNIQUE INDEX categories_child_name_uq ON categories (parent_category_id, name)
    WHERE parent_category_id IS NOT NULL;
CREATE UNIQUE INDEX categories_root_order_uq ON categories (display_order)
    WHERE parent_category_id IS NULL;
CREATE UNIQUE INDEX categories_child_order_uq ON categories (parent_category_id, display_order)
    WHERE parent_category_id IS NOT NULL;

INSERT INTO categories (code, name, display_order) VALUES
    ('GRAMMAR', '문법', 1),
    ('PRACTICAL', '실무', 2),
    ('CODING_PROBLEM', '코딩문제', 3);

INSERT INTO categories (parent_category_id, code, name, display_order)
SELECT category_id, 'PRACTICAL_CACHE', '캐시', 1 FROM categories WHERE code = 'PRACTICAL'
UNION ALL
SELECT category_id, 'PRACTICAL_DB', 'DB', 2 FROM categories WHERE code = 'PRACTICAL'
UNION ALL
SELECT category_id, 'PRACTICAL_NETWORK', '네트워크', 3 FROM categories WHERE code = 'PRACTICAL'
UNION ALL
SELECT category_id, 'PRACTICAL_LOG', '로그', 4 FROM categories WHERE code = 'PRACTICAL';

CREATE TABLE templates (
    template_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id bigint NOT NULL REFERENCES categories (category_id),
    language_id bigint REFERENCES languages (language_id),
    created_by bigint NOT NULL REFERENCES users (user_id),
    title varchar(100) NOT NULL,
    summary varchar(300) NOT NULL,
    description text NOT NULL,
    difficulty varchar(20) NOT NULL DEFAULT 'EASY'
        CHECK (difficulty IN ('EASY', 'NORMAL', 'HARD')),
    display_order integer NOT NULL CHECK (display_order > 0),
    is_published boolean NOT NULL DEFAULT false,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT templates_title_not_blank CHECK (btrim(title) <> ''),
    CONSTRAINT templates_summary_not_blank CHECK (btrim(summary) <> ''),
    CONSTRAINT templates_display_order_uq UNIQUE NULLS NOT DISTINCT
        (category_id, language_id, display_order)
);

CREATE INDEX templates_list_idx
    ON templates (category_id, language_id, is_published, display_order);

-- A template is the chapter/card; these rows are its ordered TOC items.
-- A parent row can be "1. 캐시가 필요한 상황" and a child "1-1. 적용 기준".
CREATE TABLE template_sections (
    section_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    template_id bigint NOT NULL REFERENCES templates (template_id),
    parent_section_id bigint,
    title varchar(150) NOT NULL,
    body text,
    example_code text,
    display_order integer NOT NULL CHECK (display_order > 0),
    CONSTRAINT template_sections_title_not_blank CHECK (btrim(title) <> ''),
    CONSTRAINT template_sections_not_own_parent CHECK (parent_section_id IS DISTINCT FROM section_id),
    CONSTRAINT template_sections_template_identity_uq UNIQUE (section_id, template_id),
    CONSTRAINT template_sections_parent_fk FOREIGN KEY (parent_section_id, template_id)
        REFERENCES template_sections (section_id, template_id),
    CONSTRAINT template_sections_order_uq UNIQUE NULLS NOT DISTINCT
        (template_id, parent_section_id, display_order)
);

CREATE INDEX template_sections_template_idx
    ON template_sections (template_id, parent_section_id, display_order);

CREATE TABLE questions (
    question_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id bigint NOT NULL REFERENCES categories (category_id),
    related_template_id bigint REFERENCES templates (template_id) ON DELETE SET NULL,
    related_section_id bigint,
    created_by bigint NOT NULL REFERENCES users (user_id),
    language_id bigint REFERENCES languages (language_id),
    question_type varchar(30) NOT NULL
        CHECK (question_type IN ('MULTIPLE_CHOICE', 'CODE_EXPLANATION', 'CODE_WRITING')),
    prompt text NOT NULL,
    code_snippet text,
    choice_options jsonb,
    correct_choice_key varchar(10),
    reference_answer text,
    grading_criteria jsonb,
    explanation text,
    difficulty varchar(20) NOT NULL DEFAULT 'EASY'
        CHECK (difficulty IN ('EASY', 'NORMAL', 'HARD')),
    pass_score smallint NOT NULL DEFAULT 70
        CHECK (pass_score BETWEEN 0 AND 100),
    display_order integer NOT NULL CHECK (display_order > 0),
    is_published boolean NOT NULL DEFAULT false,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT questions_prompt_not_blank CHECK (btrim(prompt) <> ''),
    CONSTRAINT questions_choice_options_array CHECK (
        choice_options IS NULL OR jsonb_typeof(choice_options) = 'array'
    ),
    CONSTRAINT questions_grading_criteria_array CHECK (
        grading_criteria IS NULL OR jsonb_typeof(grading_criteria) = 'array'
    ),
    CONSTRAINT questions_section_requires_template CHECK (
        related_section_id IS NULL OR related_template_id IS NOT NULL
    ),
    CONSTRAINT questions_section_template_fk FOREIGN KEY (related_section_id, related_template_id)
        REFERENCES template_sections (section_id, template_id)
);

CREATE INDEX questions_list_idx
    ON questions (category_id, language_id, is_published, display_order);
CREATE INDEX questions_related_template_idx ON questions (related_template_id);
CREATE INDEX questions_related_section_idx ON questions (related_section_id, display_order)
    WHERE related_section_id IS NOT NULL;
CREATE UNIQUE INDEX questions_section_order_uq
    ON questions (related_section_id, display_order)
    WHERE related_section_id IS NOT NULL;

CREATE TABLE media_files (
    media_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uploaded_by bigint NOT NULL REFERENCES users (user_id),
    template_id bigint REFERENCES templates (template_id),
    section_id bigint REFERENCES template_sections (section_id),
    question_id bigint REFERENCES questions (question_id),
    media_type varchar(20) NOT NULL
        CHECK (media_type IN ('PROFILE', 'TEMPLATE', 'SECTION', 'QUESTION')),
    object_key varchar(500) NOT NULL UNIQUE,
    original_name varchar(255) NOT NULL,
    content_type varchar(100) NOT NULL,
    file_size bigint NOT NULL CHECK (file_size > 0),
    alt_text varchar(300),
    display_order integer NOT NULL DEFAULT 0 CHECK (display_order >= 0),
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT media_files_target_matches_type CHECK (
        (media_type = 'PROFILE' AND template_id IS NULL AND section_id IS NULL AND question_id IS NULL)
        OR (media_type = 'TEMPLATE' AND template_id IS NOT NULL AND section_id IS NULL AND question_id IS NULL)
        OR (media_type = 'SECTION' AND template_id IS NULL AND section_id IS NOT NULL AND question_id IS NULL)
        OR (media_type = 'QUESTION' AND template_id IS NULL AND section_id IS NULL AND question_id IS NOT NULL)
    )
);

CREATE INDEX media_files_template_idx ON media_files (template_id, display_order)
    WHERE template_id IS NOT NULL;
CREATE INDEX media_files_section_idx ON media_files (section_id, display_order)
    WHERE section_id IS NOT NULL;
CREATE INDEX media_files_question_idx ON media_files (question_id, display_order)
    WHERE question_id IS NOT NULL;

ALTER TABLE users
    ADD CONSTRAINT users_profile_media_fk
    FOREIGN KEY (profile_media_id) REFERENCES media_files (media_id) ON DELETE SET NULL;

CREATE TABLE submissions (
    submission_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES users (user_id),
    question_id bigint NOT NULL REFERENCES questions (question_id),
    selected_choice_key varchar(10),
    answer_text text,
    source_code text,
    grading_status varchar(20) NOT NULL DEFAULT 'PENDING'
        CHECK (grading_status IN ('PENDING', 'COMPLETED', 'FAILED')),
    grading_method varchar(20)
        CHECK (grading_method IN ('DB', 'AI', 'RULE_FALLBACK')),
    score numeric(5, 2) CHECK (score BETWEEN 0 AND 100),
    feedback text,
    criteria_results jsonb,
    ai_model_version varchar(100),
    submitted_at timestamptz NOT NULL DEFAULT now(),
    graded_at timestamptz,
    CONSTRAINT submissions_one_answer CHECK (
        num_nonnulls(selected_choice_key, answer_text, source_code) = 1
    ),
    CONSTRAINT submissions_criteria_results_array CHECK (
        criteria_results IS NULL OR jsonb_typeof(criteria_results) = 'array'
    ),
    CONSTRAINT submissions_completed_has_result CHECK (
        grading_status <> 'COMPLETED'
        OR (grading_method IS NOT NULL AND score IS NOT NULL AND graded_at IS NOT NULL)
    )
);

-- Every retry is a new row. The app reads the latest row for a user/question.
CREATE INDEX submissions_latest_idx
    ON submissions (user_id, question_id, submitted_at DESC, submission_id DESC);

CREATE TABLE user_progress (
    user_id bigint NOT NULL REFERENCES users (user_id),
    template_id bigint NOT NULL REFERENCES templates (template_id),
    last_section_id bigint,
    started_at timestamptz NOT NULL DEFAULT now(),
    last_studied_at timestamptz NOT NULL DEFAULT now(),
    completed_at timestamptz,
    PRIMARY KEY (user_id, template_id),
    CONSTRAINT user_progress_last_section_fk FOREIGN KEY (last_section_id, template_id)
        REFERENCES template_sections (section_id, template_id),
    CONSTRAINT user_progress_completion_after_start CHECK (
        completed_at IS NULL OR completed_at >= started_at
    )
);

CREATE TABLE template_bookmarks (
    user_id bigint NOT NULL REFERENCES users (user_id),
    template_id bigint NOT NULL REFERENCES templates (template_id),
    created_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (user_id, template_id)
);

